### ISSUE TITLE
EvangelistExceptionTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-iadeniyi/open-source-evangelists#3]
``` php
/**
     * @dataProvider sampleInput
     *
     * @expectedException Exception
     */
    public function testNullInputException($username)
    {
        $evangelists = new EvangelistStatus($username);
    }
```

You should be testing for NullInputException specifically, but you are testing for the general Exception. If someone puts a different type of Exception in EvangelistStatus, the test would still pass regardless.

**Comment by ibonly** [comment]
@expectedException is not reading the custom exception. The issue has been resolved by using `setExpectedException` method.
